export const ipcChannels = {
  bootstrap: 'powershell-config:bootstrap',
  previewTheme: 'powershell-config:preview-theme',
  importTheme: 'powershell-config:import-theme',
  saveUserState: 'powershell-config:save-user-state',
  exportConfiguration: 'powershell-config:export-configuration',
  inspectConfigurationImport: 'powershell-config:inspect-configuration-import',
  applyConfigurationImport: 'powershell-config:apply-configuration-import',
  cancelConfigurationImport: 'powershell-config:cancel-configuration-import',
  validateCustomizations: 'powershell-config:validate-customizations',
  applySettings: 'powershell-config:apply-settings',
  restoreDefaults: 'powershell-config:restore-defaults',
  restoreLatestBackup: 'powershell-config:restore-latest-backup',
  openTerminal: 'powershell-config:open-terminal',
  openLogs: 'powershell-config:open-logs',
  quit: 'powershell-config:quit',
  notifyUnsavedCustomizations: 'powershell-config:notify-unsaved-customizations',
} as const;
